name = "foxsportscards1of1"
compatibility_date = "2024-10-19"
pages_build_output_dir = ".vercel/output/static"
compatibility_flags = ["nodejs_compat"]

[vars]
SANITY_PROJECT_ID = "xfwmlues"
SANITY_DATASET = "production"
SANITY_API_VERSION = "2024-10-01"
NEXT_PUBLIC_SANITY_PROJECT_ID = "xfwmlues"
NEXT_PUBLIC_SANITY_DATASET = "production"
NEXT_PUBLIC_SANITY_API_VERSION = "2024-10-01"
SANITY_STUDIO_PROJECT_ID = "xfwmlues"
SANITY_STUDIO_DATASET = "production"
SANITY_STUDIO_API_VERSION = "2024-10-01"
