name = "foxsportscards1of1"
account_id = "bd53fb98822531be3f735ca1af38183c"
compatibility_date = "2024-10-19"
pages_build_output_dir = ".vercel/output/static"

[build]
command = "npx --yes @cloudflare/next-on-pages@latest"

[pages]
project_name = "foxsportscards1of1"
build_output_dir = ".vercel/output/static"
